/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SmsLogService } from "../smsLog.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SmsLogCreateInput } from "./SmsLogCreateInput";
import { SmsLog } from "./SmsLog";
import { SmsLogFindManyArgs } from "./SmsLogFindManyArgs";
import { SmsLogWhereUniqueInput } from "./SmsLogWhereUniqueInput";
import { SmsLogUpdateInput } from "./SmsLogUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SmsLogControllerBase {
  constructor(
    protected readonly service: SmsLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SmsLog })
  @nestAccessControl.UseRoles({
    resource: "SmsLog",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SmsLogCreateInput,
  })
  async createSmsLog(@common.Body() data: SmsLogCreateInput): Promise<SmsLog> {
    return await this.service.createSmsLog({
      data: data,
      select: {
        createdAt: true,
        id: true,
        message: true,
        sentDate: true,
        status: true,
        to: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SmsLog] })
  @ApiNestedQuery(SmsLogFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SmsLog",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async smsLogs(@common.Req() request: Request): Promise<SmsLog[]> {
    const args = plainToClass(SmsLogFindManyArgs, request.query);
    return this.service.smsLogs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        message: true,
        sentDate: true,
        status: true,
        to: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SmsLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SmsLog",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async smsLog(
    @common.Param() params: SmsLogWhereUniqueInput
  ): Promise<SmsLog | null> {
    const result = await this.service.smsLog({
      where: params,
      select: {
        createdAt: true,
        id: true,
        message: true,
        sentDate: true,
        status: true,
        to: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SmsLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SmsLog",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SmsLogUpdateInput,
  })
  async updateSmsLog(
    @common.Param() params: SmsLogWhereUniqueInput,
    @common.Body() data: SmsLogUpdateInput
  ): Promise<SmsLog | null> {
    try {
      return await this.service.updateSmsLog({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          message: true,
          sentDate: true,
          status: true,
          to: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SmsLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SmsLog",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSmsLog(
    @common.Param() params: SmsLogWhereUniqueInput
  ): Promise<SmsLog | null> {
    try {
      return await this.service.deleteSmsLog({
        where: params,
        select: {
          createdAt: true,
          id: true,
          message: true,
          sentDate: true,
          status: true,
          to: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
