/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EmailLogService } from "../emailLog.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmailLogCreateInput } from "./EmailLogCreateInput";
import { EmailLog } from "./EmailLog";
import { EmailLogFindManyArgs } from "./EmailLogFindManyArgs";
import { EmailLogWhereUniqueInput } from "./EmailLogWhereUniqueInput";
import { EmailLogUpdateInput } from "./EmailLogUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmailLogControllerBase {
  constructor(
    protected readonly service: EmailLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EmailLog })
  @nestAccessControl.UseRoles({
    resource: "EmailLog",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: EmailLogCreateInput,
  })
  async createEmailLog(
    @common.Body() data: EmailLogCreateInput
  ): Promise<EmailLog> {
    return await this.service.createEmailLog({
      data: data,
      select: {
        body: true,
        createdAt: true,
        id: true,
        sentDate: true,
        status: true,
        subject: true,
        to: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EmailLog] })
  @ApiNestedQuery(EmailLogFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EmailLog",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emailLogs(@common.Req() request: Request): Promise<EmailLog[]> {
    const args = plainToClass(EmailLogFindManyArgs, request.query);
    return this.service.emailLogs({
      ...args,
      select: {
        body: true,
        createdAt: true,
        id: true,
        sentDate: true,
        status: true,
        subject: true,
        to: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EmailLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailLog",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emailLog(
    @common.Param() params: EmailLogWhereUniqueInput
  ): Promise<EmailLog | null> {
    const result = await this.service.emailLog({
      where: params,
      select: {
        body: true,
        createdAt: true,
        id: true,
        sentDate: true,
        status: true,
        subject: true,
        to: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EmailLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailLog",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: EmailLogUpdateInput,
  })
  async updateEmailLog(
    @common.Param() params: EmailLogWhereUniqueInput,
    @common.Body() data: EmailLogUpdateInput
  ): Promise<EmailLog | null> {
    try {
      return await this.service.updateEmailLog({
        where: params,
        data: data,
        select: {
          body: true,
          createdAt: true,
          id: true,
          sentDate: true,
          status: true,
          subject: true,
          to: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EmailLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailLog",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEmailLog(
    @common.Param() params: EmailLogWhereUniqueInput
  ): Promise<EmailLog | null> {
    try {
      return await this.service.deleteEmailLog({
        where: params,
        select: {
          body: true,
          createdAt: true,
          id: true,
          sentDate: true,
          status: true,
          subject: true,
          to: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
